"""Initial zyra migration

Revision ID: 3c0d7e4bf48f
Revises: 
Create Date: 2026-01-08 04:01:07.198472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0d7e4bf48f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zyra_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('artist', sa.String(length=120), nullable=False),
    sa.Column('album', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zyra_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('zyra_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zyra_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zyra_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_zyra_user_username'), ['username'], unique=True)

    op.create_table('zyra_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['zyra_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zyra_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zyra_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['zyra_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zyra_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['zyra_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zyra_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zyra_user_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['zyra_music.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['zyra_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'music_id')
    )
    op.create_table('zyra_playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['zyra_music.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['zyra_playlist.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'music_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zyra_playlist_songs')
    op.drop_table('zyra_user_likes')
    op.drop_table('zyra_subscription')
    op.drop_table('zyra_playlist')
    op.drop_table('zyra_payment')
    with op.batch_alter_table('zyra_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zyra_user_username'))
        batch_op.drop_index(batch_op.f('ix_zyra_user_email'))

    op.drop_table('zyra_user')
    op.drop_table('zyra_plan')
    op.drop_table('zyra_music')
    # ### end Alembic commands ###
